### ISSUE TITLE
Permissions error during npm run build

### ISSUE THREAD

**Issue by GeorgeHricoAtBentley** [imodeljs/simple-viewer-app#3]
When attempting to do "npm run build" step I get the following:

Error { Error: EPERM: operation not permitted, symlink 'C:\Code\simple-viewer-app\node_modules\@bentley\bentleyjs-core\lib\module\dev\bentleyjs-core.js' -> 'C:\Code\simple-viewer-app\lib\webresources\v-latest\bentleyjs-core.js'
    at Object.symlinkSync (fs.js:905:3)
    at linkModuleFile (C:\Code\simple-viewer-app\node_modules\@bentley\webpack-tools\modules\copyExternalModules.js:93:8)
    at main (C:\Code\simple-viewer-app\node_modules\@bentley\webpack-tools\modules\copyExternalModules.js:201:13)
    at Object.<anonymous> (C:\Code\simple-viewer-app\node_modules\@bentley\webpack-tools\modules\copyExternalModules.js:223:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
  errno: -4048,
  syscall: 'symlink',
  code: 'EPERM',
  path:
   'C:\\Code\\simple-viewer-app\\node_modules\\@bentley\\bentleyjs-core\\lib\\module\\dev\\bentleyjs-core.js',
  dest:
   'C:\\Code\\simple-viewer-app\\lib\\webresources\\v-latest\\bentleyjs-core.js' }

**Comment by williamkbentley** [comment]
That looks like a permissions error during the symlinking. Can you try running your shell as Administrator to get around it?

**Comment by GeorgeHricoAtBentley** [comment]
Thanks, that works.
