### ISSUE TITLE
 error：“npm run start:backend  ” 

### ISSUE THREAD

**Issue by JiaoFu1973** [imodeljs/simple-viewer-app#4]
node -v
v10.15.1

npm run start:backend

> node lib/backend/main.js

internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
\\?\E:\CompanySVN\47_2018-12-01_BIM\Project\Code\simple-viewer-app\trunk\node_modules\@bentley\imodeljs-native\imodeljs-win32-x64\imodeljs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.exports.loadNativePlatform (E:\CompanySVN\47_2018-12-01_BIM\Project\Code\simple-viewer-app\trunk\node_modules\@bentley\imodeljs-native\loadNativePlatform.js:28:12)
    at Function.load (E:\CompanySVN\47_2018-12-01_BIM\Project\Code\simple-viewer-app\trunk\node_modules\@bentley\imodeljs-backend\lib\IModelHost.js:139:71)
    at Function.loadNative (E:\CompanySVN\47_2018-12-01_BIM\Project\Code\simple-viewer-app\trunk\node_modules\@bentley\imodeljs-backend\lib\IModelHost.js:66:69)
    at Function.startup (E:\CompanySVN\47_2018-12-01_BIM\Project\Code\simple-viewer-app\trunk\node_modules\@bentley\imodeljs-backend\lib\IModelHost.js:82:22)

**Comment by rajgadade** [comment]
We were facing the same problem.  here are things we tried to fix this issue

Ensure that you have installed @bentley/imodeljs-win32-x64  npm package . if not, then install it "npm install @bentley/imodeljs-win32-x64".

Also, make sure that "imodeljs.node" file is available at E:\CompanySVN\47_2018-12-01_BIM\Project\Code\simple-viewer-app\trunk\node_modules@bentley\imodeljs-native\imodeljs-win32-x64\imodeljs.node

if you are still getting an error, then there might be a problem with iModel native API dependency dll. this "iModel native API" depends on VCRUNTIME140.DLL, MSVCP140.DLL (and maybe a NAPI.DLL). If one of these DLL is not loaded properly then it gives an error as you mentioned.

To fix the DLLs issue, You can download and install The Visual C++ Redistributable Packages (vc_redist.x64.exe) from Microsoft site https://www.microsoft.com/en-us/download/details.aspx?id=48145 

Now, rerun the start command. Hope, this will fix your issues.

Good luck..!

**Comment by roopsaini** [comment]
@JiaoFu1973,

Which version of windows are you using? Some users were having this issue on Windows 7. There is a fix that will be released within the next few days.

**Comment by roopsaini** [comment]
@JiaoFu1973, The fix has been pushed. If you're still having the issue, could you please try again?

**Comment by calebmshafer** [comment]
Closing due to inactivity.  If the issue persists, please open a new issue.

Thanks!
